### ISSUE TITLE
No wheels for python 3.11

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy#82]
Python 3.11 is out and already available on conda-forge, could we release y-py with wheels for it?

**Comment by encukou** [comment]
Would it be worth it to build for Python's stable ABI, so the built wheels are compatible across Python versions?
I'm not familiar with Rust (though I can help with Python stable ABI), but it [should be possible](https://www.maturin.rs/tutorial.html?highlight=stable#create-a-new-rust-project) with:
```toml
[dependencies.pyo3]
features = ["extension-module", "abi3-py37"]
```
(The resulting wheel should still be *tested* on all supported Python versions.)
